# Site
repository: fanyimeng0/fanyimeng0.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2
title: M.Phil Student CUHK(SZ)
# Personal info
name: Fanyi Meng  
#job_title: M.Phil Candidate
phone: (+86)18935106029
email: fanyimeng@link.cuhk.edu.cn
company: The Chinese University of Hong Kong,Shenzhen

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: fanyimeng0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: carlo.mfy
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#000youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-3981-0003
#wechat_username: M18935106029

# Additional icon links
additional_links:
  #- title: itsgoingto.be
  #  icon: fas fa-globe
  #  url: https://www.itsgoingto.be
  #- title: another link
  #  icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #  url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pre2.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fanyi Meng and I'm pursuing my M.Phil of Computer and Information Engineering in The Chinese University of Hong Kong, Shenzhen (CUHKSZ). 
  I am co-supervised by [Dr. Guangxu Zhu](https://sites.google.com/view/guangxuzhu) and [Prof Tsung-Hui Chang](https://sse.cuhk.edu.cn/faculty/tsunghuichang).

  I received B.Eng from Southern University of Technology (Sustech) in Communication Engineering in 2023.
  
  My research interests include sensing-assisted communication, integrated sensing and communication (ISAC), and wireless simulation. I am looking for a Ph.D. program in ECE or CSE for the year 2025. If there are any available openings, please inform me via email!

  [My Resume](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/CV_Fanyi%20MENG.pdf)  [Research Proposal ](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/Research Proposal.pdf)

content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wi-Fi QoS
        caption: Jun 2022 - Feb 2023
        # link: github.com/your-username
        # link_text: github.com/fanyimeng0/ns3-wifi-edcatest
        additional_links:
          - title: ns3-wifi-edcatest
            icon: fab fa-github
            url: https://github.com/fanyimeng0/ns3-wifi-edcatest
        quote: >
          Improving overall QoS performance by changing EDCA parameters.
        description: | # this will include new lines to allow paragraphs
          Utilized MATLAB's WLAN Toolbox for simulation of the Distributed Coordination Function (DCF) within the Wi-Fi MAC layer.

          Utilized NS-3 to analyze the Enhanced Distributed Channel Access (EDCA) mechanism in 802.11ac, focusing on throughput and latency.

          Refined EDCA parameters to achieve Proportional Fairness in Channel Allocation for WiFi networks. 

          Verified our results in Linux 5.15 by Hacking Wi-Fi Driver. More detail in (https://github.com/iamhyc/wlsops-hack)

          ![Wi-Fi Qos GIF](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/wifiqos.gif)

      - layout: left
        title: Wi-Fi Sensing
        caption: Mar 2023 - Present
        quote: >
          Utilizing Wi-Fi signals for human health monitoring.
        description: | # this will include new lines to allow paragraphs
          Extracted Channel State Information (CSI) from Wi-Fi signals using Intel 5300 and RT-AC86U.

          Built a platform to simultaneously collect CSI data on three devices for network training.

          Used 3 Intel 5300 to track and localize people in real-time. Patent application acceptance (202311295755.4).

          ![Wi-Fi Sensing GIF](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/wifisensing.gif)


      - layout: left
        title: ISAC Performance Modeling
        caption: Mar 2023 - Present
        quote: >
          Data-driven Approach for Integrated Sensing and Communication Performance Modeling
        description: | # this will include new lines to allow paragraphs
          Using Nvidia Sionna to simulate sensing data in ISAC Networks.

          Using Machine Learning to analyze the sensing performance (e.g., localization coverage).

          Using the model to optimize the sensing performance by changing BS parameters.

  - title: Awards # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      3rd Prize, the First Wi-Fi Sensing Contest Dec. 2023

      Advanced to the semifinals in International Algorithm Competition of Pazhou Lab Nov 2023

  - title: Academic Services
    layout: list
    content:
      - layout: left
        title: Reviewer
        description: | # this will include new lines to allow paragraphs
          IEEE International Conference on Computer and Communications (ICCC), 2023

          IEEE Global Communications Conference Workshop (Globecom), 2023

          IEEE Vehicular Technology Conference (VTC), 2023

          IEEE International Conference on Wireless Communications and Signal Processing (WCSP), 2024

          IEEE International Conference on Acoustics, Speech, and Signal Processing (ICASSP), 2024

          IEEE Transactions on Wireless Communication (TWC), 2024

          IEEE International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC), 2024

#footer_show_references: true 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
