# Site
repository: fanyimeng0/fanyimeng0.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2
title: M.Phil Student CUHK(SZ)
# Personal info
name: Fanyi Meng  
#job_title: M.Phil Candidate
phone: (+86)18935106029
email: fanyimeng@link.cuhk.edu.cn
company: The Chinese University of Hong Kong,Shenzhen


# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  fanyimeng0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: carlo.mfy
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#000youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-3981-0003
#wechat_username: M18935106029

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pre2.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fanyi Meng and I'm persuing my M.Phil of Computer and Information Engineering in The Chinese University of Hong Kong, Shenzhen(CUHKSZ). 
  I am co-supervised by [Dr. Guangxu Zhu](https://sites.google.com/view/guangxuzhu) and [Prof Tsung-Hui Chang](https://sse.cuhk.edu.cn/faculty/tsunghuichang).

  I received B.Eng from Southern University of Technology(Sustech) in Communication Engineering in 2023.
  
  My resarch interests include enviroment-aware communication, integrated sensing and communication(ISAC), collaborative perception and SLAM. And I am looking for a Ph.D. program in ECE or CSE for the year 2025. If there are any available openings, please inform me via email!

  [My Resume](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/CV_Fanyi%20MENG.pdf)  [Research Proposal(Ongoing)]

  
content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wi-Fi Qos
        caption: Jun 2022 - Feb 2023
        
        quote: >
          Improving overall QoS performance by changing EDCA parameters.
        description: | # this will include new lines to allow paragraphs
          We Utilized MATLAB's WLAN Toolbox for simulation of the Distributed Coordination Function (DCF) within the Wi-Fi MAC layer.

          We Utilized NS-3 to analyze the Enhanced Distributed Channel Access (EDCA) mechanism in 802.11ac, focusing on throughput and latency.

          We Refined EDCA parameters to achieve Proportional Fairness in Channel Allocation for WiFi networks.



      - layout: left
        title: Wi-Fi Sensing
        caption: Mar 2023 - Present
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Utilizing Wi-Fi signals for human health monitoring.
        description: | # this will include new lines to allow paragraphs
         We Extracted Channel State Information (CSI) from Wi-Fi signals using Intel 5300 and RT-AC86U.

         We built a platform to simultaneously collect CSI data on three devices for network training.

         We used 3 Intel 5300 to track and localize people in real-time. Patent application acceptance(202311295755.4).

         (Ongoing) Improving algorithm accuracy by jointly using Angle of Arrival (AOA) and Doppler Frequency Shift/Time of Flight (DFS/TOF).
         
      - layout: left
        title: Sening-aided Communication
        caption: Oct 2023 - Present
        
        quote: >
          Using sensor data (visual/radar) to enhance communication performance
        description: | # this will include new lines to allow paragraphs
          (Ongoing) Utilizing Sionna for simulating coverage maps.

          (Ongoing) Utilizing cameras with different perspectives to reduce the overhead of beam prediction.

  
  - title: Awards # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
          3rd Prize, the First Wi-Fi Sensing Contest Dec. 2023

          Advanced to the semifinals in International Algorithm Competition of Pazhou Lab Nov 2015

  - title: Academic Services
    layout: list
    content:
    - layout: left
      title: Reviewer
      description: | # this will include new lines to allow paragraphs
        IEEE International Conference on Computer and Communications(ICCC)

        IEEE Global Communications Conference Workshop(Globecom)

        IEEE Vehicular Technology Conference(VTC)

        IEEE Communications Magazine

        IEEE International Conference on Wireless Communications and Signal Processing(WCSP)
   



#footer_show_references: true 

#footer_show_references: true 
 
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
