# Site
repository: fanyimeng0/fanyimeng0.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2
title: M.Phil Candidate CUHK(SZ)
# Personal info
name: Fanyi Meng  
#job_title: M.Phil Candidate
phone: (+86)18935106029
email: fanyimeng@link.cuhk.edu.cn
company: The Chinese University of Hong Kong,Shenzhen

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: fanyimeng0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: carlo.mfy
linkedin_username: fanyi-meng-24013531b
# xing_username: jekyll
# pinterest_username: jekyll
#000youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-3981-0003
#wechat_username: M18935106029

# Additional icon links
additional_links:
  #- title: itsgoingto.be
  #  icon: fas fa-globe
  #  url: https://www.itsgoingto.be
  - title: Google Scholar link
    #icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
    icon: fas fa-graduation-cap
    url: https://scholar.google.com/citations?user=cCaBzvQAAAAJ&hl=en

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pre2.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fanyi Meng and I have obtained my M.Phil degree in Computer and Information Engineering from The Chinese University of Hong Kong, Shenzhen (CUHKSZ).
  I am co-supervised by [Dr. Guangxu Zhu](https://sites.google.com/view/guangxuzhu) and [Prof Tsung-Hui Chang](https://sse.cuhk.edu.cn/faculty/tsunghuichang).

  I received B.Eng from Southern University of Technology (Sustech) in Communication Engineering in 2023, supervised by [Prof Rui Wang](http://lasso.eee.sustech.edu.cn/).
  
  My research interests include Integrated Sensing and Communication (ISAC), Digital Twin and Differentiable Rendering. I am looking for a Ph.D. program in ECE or CSE for the year 2025/2026. If there are any available openings, please inform me via email!

  [My Resume](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/CV_Fanyi-MENG.pdf)       
#[My Research Proposal ](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/Research Proposal.pdf)

content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wi-Fi QoS
        caption: Jun 2022 - Feb 2023
        # link: github.com/your-username
        # link_text: github.com/fanyimeng0/ns3-wifi-edcatest
        additional_links:
          - title: ns3-wifi-edcatest
            icon: fab fa-github
            url: https://github.com/fanyimeng0/ns3-wifi-edcatest
        quote: >
          Improving overall QoS performance by changing EDCA parameters.
        description: | # this will include new lines to allow paragraphs
          Utilized MATLAB's WLAN Toolbox for simulation of the Distributed Coordination Function (DCF) within the Wi-Fi MAC layer.

          Utilized NS-3 to analyze the Enhanced Distributed Channel Access (EDCA) mechanism in 802.11ac, focusing on throughput and latency.

          Refined EDCA parameters to achieve Proportional Fairness in Channel Allocation for WiFi networks. Patent application acceptance (202310862296.7)(202310857615.5).

          Verified our results in Linux 5.15 by Hacking Wi-Fi Driver. More detail in (https://github.com/iamhyc/wlsops-hack)

          ![Wi-Fi Qos GIF](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/wifiqos.gif)

      - layout: left
        title: Wi-Fi Sensing System 
        caption: Mar 2023 - April 2024
        additional_links:
          - title: Wi-Fi Sensing System
            icon: fab fa-github
            url: https://github.com/fanyimeng0/Witraj_real-time-python-
        quote: >
          Utilizing Wi-Fi signals for human health monitoring.
        description: | # this will include new lines to allow paragraphs

          Extracted Channel State Information (CSI) from Wi-Fi signals on Intel 5300 NIC, ESP32, and Router RT-AC86U.
         
          Built a Wi-Fi Sensing System for data collection, model training, and function visualization.
          
          Used BERT-based neural network to address packet loss challenges in Wi-Fi Sensing tasks.
          
          Employed three Intel 5300 NICs for sub-2-second latency in real-time human tracking and localization.



          ![Wi-Fi Sensing GIF](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/wifisensing.gif)


      - layout: left
        title: 6G Network Performance Simulation and Optimization
        caption: June 2024 - Present
        quote: >
          Building a 6G network performance simulation platform building upon Nvidia Sionna.
        description: | # this will include new lines to allow paragraphs
          Calibrating Sionna Ray-tracing(RT) models with real-world beam-wise RSRP.

          Simulating system-level network performance metrics (e.g., Spatial Efficiency, Localization Error) incorporating advanced 6G technologies (RIS,ISAC).
          
          Optimizing network performance using gradient-based methods, leveraging the chain rule for differentiation within Sionna's Ray-tracing and Neural Network components.
 
          ![Simulation Platform Photo](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/p1-v10.png)

      - layout: left
        title: Taichi RT
        caption: Feb 2025 - Present
        quote: > 
          Impplementing a differentiable and parrllel radio ray-tracing simulator on GPU based on Taichi lang.
        description: | # this will include new lines to allow paragraphs
          Support specular reflection and BVH acceleration based on Taichi.

          Support differentiable ray-tracing with respect to electromagnetic parameters(e.g., conductivity).

          (Ongoing)Implementing diffuse reflection and refraction.

          (Ongoing)Implementing radio map simulation.

          ![Taichi Simulation](https://raw.githubusercontent.com/fanyimeng0/fanyimeng0.github.io/main/assets/Taichi.png)
          
  - title: Publication # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      [1] **Fanyi Meng**, Xinhao Li, Dongzhu Liu, Guangxu Zhu. **Environment Calibrated and Fully Differentiable Wireless Network Simulator for 6G** Submitted to IEEE for possible publication 
      
      [2] Zhao, Zijian, **Fanyi Meng**, Hang Li, Xiaoyang Li, and Guangxu Zhu. **Mining Limited Data Sufficiently: A BERT-inspired Approach for CSI Time Series Application in Wireless Communication and Sensing.**arXiv preprint arXiv:2412.06861 (2024).<a href="https://arxiv.org/pdf/2412.06861" style="text-decoration: underline;">Paper</a>

      [3] Zhao, Zijian, Tingwei Chen, **Fanyi Meng**, Hang Li, Xiaoyang Li, and Guangxu Zhu. **Finding the Missing Data: A BERT-inspired Approach Against Package Loss in Wireless Sensing**. in IEEE INFOCOM DeepWireless Worshop 2024.
      <a href="https://arxiv.org/abs/2403.12400" style="text-decoration: underline;">Paper</a> <a href="https://github.com/RS2002/CSI-BERT" style="text-decoration: underline;">Github</a>


      [4] Yihang Jiang, **Fanyi Meng**, Xinhao Li, Xiaoyang Li, Guangxu Zhu, Kaifeng Han, Qingjiang Shi **Coverage Analysis for Air-Ground Integrated-Sensing-and-Communication Networks** in International Conference on Ubiquitous Communication 2024. <a href="https://ieeexplore.ieee.org/abstract/document/10695929" style="text-decoration: underline;">Paper</a>

      [5] Xinhao Li, Yihang Jiang, **Fanyi Meng**, Xiaoyang Li, Kaifeng Han, Guangxu Zhu **Integrated Sensing and Communications Signal Prediction with Multi-Beam Statistical Channel** In 2024 International Symposium on Antennas and Propagation (ISAP), pp. 1-2. IEEE, 2024. <a href="https://ieeexplore.ieee.org/document/10846363" style="text-decoration: underline;">Paper</a>

      

  - title: Awards # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      3rd Prize, the First Wi-Fi Sensing Contest , Huawei, Dec. 2023 [Link](https://mp.weixin.qq.com/s/16cauCbcHotlCYzBtyT0DQ)

      Advanced to the semifinals in International Algorithm Competition of Pazhou Lab Nov 2023

  - title: Academic Services
    layout: list
    content:
      - layout: left
        title: Reviewer
        description: | # this will include new lines to allow paragraphs

          IEEE Communication Magazine, 2024

          IEEE International Conference on Computer and Communications (ICCC), 2023

          IEEE Global Communications Conference Workshop (Globecom), 2023

          IEEE Vehicular Technology Conference (VTC), 2023

          IEEE International Conference on Wireless Communications and Signal Processing (WCSP), 2024

          IEEE International Conference on Acoustics, Speech, and Signal Processing (ICASSP), 2024

          IEEE Transactions on Wireless Communication (TWC), 2024

          IEEE International Symposium on Personal, Indoor and Mobile Radio Communications (PIMRC), 2024

#footer_show_references: true 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
